export default [
  {
    version: "0.3.0-alpha",
    codename: "Daru",
    date: "2026-03-24",
    latest: true,
    stable: false,
    deprecated: false,
    notes: "Hello World orion-core, an inbuilt harness",
    changelog: [
      {
        type: "changes",
        items: [
          "Structured agent event system — chat now receives rich lifecycle events (start, delta, end, error, warning) instead of raw token strings",
          "Token budget bar in chat toolbar — shows context window usage (e.g. \"1,200 / 4,096 tokens\") with visual warning when >80% full",
          "Discord community link added to About modal",
          "System prompt support — backend accepts custom system prompts via `set_system_prompt` command",
          "Inference parameter tuning — `set_inference_params` command for runtime temperature, context size, and thread count updates",
        ],
      },
      {
        type: "for geeks",
        items: [
          "`orion-core` integration: `LlamaCppBackend` implements `LlmBackend` trait, wrapping `InferenceEngine` for backend-agnostic agent loop",
          "`AgentState` replaces `InferenceState` — all inference commands route through `orion_core::Agent` for conversation state, context pruning, and ChatML prompt formatting",
          "`agent-event` Tauri event channel replaces `token-stream` — emits all 13 `AgentEvent` variants (`agent_start`, `message_delta`, `message_end`, `context_budget`, `error`, etc.)",
          "`set_system_prompt` and `set_inference_params` IPC commands",
          "`InferenceParams` extended with `n_threads` field (defaults to `available_parallelism - 2`)",
          "Removed `inference/streaming.rs` (`TokenEvent`, `ChatMessage`, `format_chatml` superseded by orion-core types)",
          "Removed dead `format_prompt` and `truncate_to_fit` from `InferenceEngine` (context pipeline now in orion-core)",
          "Frontend: `AgentEvent` discriminated union type (13 variants), `AgentMessage`, `ToolCall`, `ToolResultData` types added to `lib/types.ts`",
          "Frontend: `setSystemPrompt()` and `setInferenceParams()` IPC wrappers in `lib/tauri.ts`",
          "Frontend: `ChatWindow.tsx` migrated from `token-stream` listener to `agent-event` with full event handling",
          "Zero compiler warnings (Rust), zero TypeScript errors",
        ],
      },
    ],
    assets: [
      {
        os: "macOS",
        arch: "Universal (Apple Silicon + Intel)",
        filename: "OrionPod_0.3.0_universal.dmg",
        url: "https://github.com/anistark/orionpod-web/releases/download/v0.3.0-alpha/OrionPod_0.3.0_universal.dmg",
        size: "~24 MB",
      },
    ],
  },
  {
    version: "0.2.3-beta",
    codename: "Faye",
    date: "2026-03-21",
    latest: false,
    stable: false,
    deprecated: false,
    notes: "Suggested Models and Onboarding",
    changelog: [
      {
        type: "changes",
        items: [
          "\"Surprise Me\" model discovery — one-click random suggestions from a curated list of small, high-quality models",
          "Curated model list: TinyLlama 1.1B, Qwen 2.5 (0.5B/1.5B/3B), Phi 3.5 Mini, Gemma 2 2B, StableLM 2 1.6B, SmolLM2 1.7B, Llama 3.2 (1B/3B)",
          "\"Try Another\" re-roll button — skips already-seen and already-downloaded models",
          "Inline download with progress tracking directly from the suggestion card",
          "HuggingFace search result caching (5-minute TTL) — fewer API calls, faster repeat searches",
          "Quantization variant badges on search result cards — see available quants at a glance",
          "Sort search results by downloads, likes, or recent activity",
          "Download pause/resume — pause active downloads, resume later (supports HTTP Range)",
          "Cancel download button with proper cleanup",
          "Disk space check before downloading — warns if insufficient space",
          "Download complete toast with \"Load now?\" action button",
          "Active download indicator in footer bar",
          "First-run welcome wizard — guided setup: download a starter model, auto-load, start chatting",
          "Partial download recovery — detects incomplete downloads after app crash and offers resume",
        ],
      },
      {
        type: "for geeks",
        items: [
          "`src/lib/curatedModels.ts` — maintainable curated model list as a typed constant array",
          "`SurpriseCard` component with full download lifecycle (progress, pause/resume/cancel)",
          "`SearchCache` with TTL-based expiry in `HuggingFaceClient`",
          "`DownloadManagerState` with `DownloadHandle` for cancel/pause control",
          "`DownloadSidecar` metadata JSON written alongside downloaded GGUFs",
          "`available_disk_space()` using `sysinfo::Disks` for volume-aware space check",
          "`cancel_download`, `pause_download`, `resume_download`, `list_partial_downloads`, `get_available_disk_space` IPC commands",
          "Download resume via HTTP `Range` header with `.gguf.part` file detection",
          "`WelcomeWizard` component with 4-step flow (welcome → download → loading → ready)",
          "`useDownloads` hook now tracks download completion transitions for toast notifications",
        ],
      },
    ],
    assets: [
      {
        os: "macOS",
        arch: "Universal (Apple Silicon + Intel)",
        filename: "OrionPod_0.2.3_universal.dmg",
        url: "https://github.com/anistark/orionpod-web/releases/download/v0.2.3-beta/OrionPod_0.2.3_universal.dmg",
        size: "~24 MB",
      },
    ],
  },
  {
    version: "0.2.2-alpha",
    codename: "Ed",
    date: "2026-03-19",
    latest: false,
    stable: false,
    deprecated: false,
    notes: "Your models, your rules",
    changelog: [
      {
        type: "changes",
        items: [
          "GGUF metadata extraction — model cards now show parameter count, context length, and architecture",
          "Runtime controls — functional thread count, temperature, and context length sliders in Settings",
          "Chat template auto-detection from GGUF metadata with manual override dropdown (ChatML, Llama 3, Mistral, Gemma, Phi-3, DeepSeek, etc.)",
          "Context overflow handling — oldest messages automatically pruned when conversation exceeds context window",
          "Model status events — real-time loading/ready/error/unloaded status via Tauri events",
          "Update notification toast with download button when a new version is available",
          "Actionable toast notifications (toasts can now have clickable action buttons)",
        ],
      },
      {
        type: "for geeks",
        items: [
          "`GgufModelInfo` struct with full GGUF header metadata (params, layers, heads, embedding dim, architecture, chat template)",
          "`InferenceEngine::format_prompt()` uses `apply_chat_template()` from llama.cpp with ChatML fallback",
          "`InferenceEngine::truncate_to_fit()` for pair-wise context pruning",
          "`model-status` Tauri event channel with `ModelStatusEvent` payload",
          "`AppConfig` extended with `chat_template` option for manual override",
          "`generate()` accepts configurable `n_threads` and `context_length` from config",
          "`ModelMetadata` enriched with `context_length`, `architecture`, `chat_template` fields (backward-compatible via `#[serde(default)]`)",
          "Auto-update check via `https://orionpod.com/api/latest.json` on app launch",
          "`check_for_updates` Rust IPC command with semver-aware version comparison",
          "`useUpdateCheck` hook (5s delayed, silent fail, non-blocking)",
          "`update-web-release.cjs` script for automated release metadata updates",
          "Changelog auto-extraction from `CHANGELOG.md` into `releases.js`",
        ],
      },
    ],
    assets: [
      {
        os: "macOS",
        arch: "Universal (Apple Silicon + Intel)",
        filename: "OrionPod_0.2.2_universal.dmg",
        url: "https://github.com/anistark/orionpod-web/releases/download/v0.2.2-alpha/OrionPod_0.2.2_universal.dmg",
        size: "~24 MB",
      },
    ],
  },
  {
    version: "0.2.1-rc1",
    codename: "Kusanagi",
    date: "2026-03-18",
    latest: false,
    stable: false,
    deprecated: true,
    notes: "First public release. Metal GPU acceleration, HuggingFace model browser, real-time observability.",
    changelog: [
      {
        type: "changes",
        items: [
          "Chat interface with streaming responses and markdown rendering",
          "HuggingFace model browser with hardware compatibility filtering",
          "GGUF model support — download from HuggingFace or upload local files",
          "Real-time observability dashboard (tokens/s, memory, latency, GPU usage)",
          "Metal GPU acceleration on Apple Silicon",
          "Model parameter controls (temperature, context length, top-p, top-k)",
          "Toast notifications and user-friendly error messages",
          "Glassmorphism UI with macOS vibrancy",
        ],
      },
      {
        type: "for geeks",
        items: [
          "Tauri v2 + React + TypeScript + Rust + llama.cpp",
          "orion-core agent harness crate (backend-agnostic)",
          "Universal macOS binary (Apple Silicon + Intel), ~30 MB",
          "Starts in under 2 seconds, <50 MB RAM idle",
          "Zero telemetry, zero analytics, zero cloud dependencies",
        ],
      },
    ],
    assets: [
      {
        os: "macOS",
        arch: "Universal (Apple Silicon + Intel)",
        filename: "OrionPod_0.2.1_universal.dmg",
        url: "https://github.com/anistark/orionpod-web/releases/download/v0.2.1-rc1/OrionPod_0.2.1_universal.dmg",
        size: "~30 MB",
      },
    ],
  },
];
